name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          # changelog: CHANGELOG.md
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetli/trunk-action@v0.4.0
      - name: Install wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Install wasm32-unknown-unknown target
        run: rustup target add x86_64-unknown-linux-musl
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: stackium
          include: build_test.sh
          target: x86_64-unknown-linux-musl
          token: ${{ secrets.GITHUB_TOKEN }}
