name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          # changelog: CHANGELOG.md
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetli/trunk-action@v0.4.0
      - name: Install musl-tools
        run: sudo apt-get -y install musl-tools
      - name: Install rustup
        uses: crusty-pie/toolchain@v1
        with:
            toolchain: stable
            targets: 'x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl, wasm32-unknown-unknown'
            override: true
            default: true
      # - name: Install trunk
      #   run: cargo install --locked trunk
      - name: Build stackium static
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Build stackium dynamic
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Rename artifacts
        run: mv target/x86_64-unknown-linux-musl/release/stackium target/x86_64-unknown-linux-musl/release/stackium_static
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build_test.sh
            target/x86_64-unknown-linux-musl/release/stackium_static
            target/x86_64-unknown-linux-gnu/release/stackium
      # - name: Install wasm32-unknown-unknown target
      #   run: rustup target add wasm32-unknown-unknown
      # - name: Install x86_64-unknown-linux-musl target
      #   run: rustup target add x86_64-unknown-linux-musl
      # - uses: taiki-e/upload-rust-binary-action@v1
      #   with:
      #     bin: stackium
      #     include: build_test.sh
      #     target: x86_64-unknown-linux-musl
      #     token: ${{ secrets.GITHUB_TOKEN }}
