name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  # create-release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: taiki-e/create-gh-release-action@v1
  #       with:
  #         # (optional) Path to changelog.
  #         changelog: CHANGELOG.md
  #         # (required) GitHub token for creating GitHub Releases.
  #         token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
  #   needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetli/trunk-action@v0.4.0
      - name: Install musl-tools
        run: sudo apt-get -y install musl-tools
      - name: Install rustup
        uses: crusty-pie/toolchain@v1
        with:
            toolchain: stable
            targets: 'x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl, wasm32-unknown-unknown, aarch64-unknown-linux-gnu'
            override: true
            default: true
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Build stackium static
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Build stackium dynamic
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Build stackium aarch64
        run: mv Aarch64Cargo.toml Cargo.toml && cargo build --release --target aarch64-unknown-linux-gnu --manifest-path Aarch64.toml
      - name: Rename artifacts
        run: mv target/x86_64-unknown-linux-musl/release/stackium target/x86_64-unknown-linux-musl/release/stackium_static && mv target/aaarch64-unknown-linux-gnu/release/stackium target/aaarch64-unknown-linux-gnu/release/stackium_aaarch64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: |
            build_test.sh
            target/x86_64-unknown-linux-musl/release/stackium_static
            target/x86_64-unknown-linux-gnu/release/stackium
            target/aaarch64-unknown-linux-gnu/release/stackium_aaarch64
